/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.cafe.ui;

import javax.swing.ImageIcon;
import poly.cafe.util.XAuth;
import poly.cafe.util.XDialog;
import poly.cafe.util.XIcon;

/**
 *
 * @author hungp
 */
public class PolyCafeJFrame extends javax.swing.JFrame implements PolyCafeController{

    /**
     * Creates new form PolyCafeJFrame
     */
    public PolyCafeJFrame() {
        initComponents();
        this.init();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuLeft = new javax.swing.JPanel();
        lblFullname = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        btnSales = new javax.swing.JButton();
        btnTrangChu = new javax.swing.JButton();
        btnQuanLySP = new javax.swing.JButton();
        btnQuanLyHD = new javax.swing.JButton();
        btnQuanLyNV = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        pnlCurrentBillInfo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblCurrentBillId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCurrentBillTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlProductListDisplay = new javax.swing.JPanel();
        pnlProductItem1 = new javax.swing.JPanel();
        lblProductItem1Image = new javax.swing.JLabel();
        lblProductItem1Name = new javax.swing.JLabel();
        lblProductItem1Price = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnProductItem1Minus = new javax.swing.JButton();
        btnProductItem1Plus = new javax.swing.JButton();
        txtProductItem1Quantity = new javax.swing.JLabel();
        pnlProductItem2 = new javax.swing.JPanel();
        lblProductItem2Image = new javax.swing.JLabel();
        lblProductItem2Price = new javax.swing.JLabel();
        lblProductItem2Name = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnProductItem1Minus1 = new javax.swing.JButton();
        btnProductItem1Plus1 = new javax.swing.JButton();
        txtProductItem1Quantity1 = new javax.swing.JLabel();
        pnlProductItem4 = new javax.swing.JPanel();
        lblProductItem4Image = new javax.swing.JLabel();
        lblProductItem4Name = new javax.swing.JLabel();
        lblProductItem4Price = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnProductItem1Minus4 = new javax.swing.JButton();
        btnProductItem1Plus4 = new javax.swing.JButton();
        txtProductItem1Quantity4 = new javax.swing.JLabel();
        pnlProductItem3 = new javax.swing.JPanel();
        lblProductItem3Image = new javax.swing.JLabel();
        lblProductItem3Price = new javax.swing.JLabel();
        lblProductItem3Name = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnProductItem1Minus2 = new javax.swing.JButton();
        btnProductItem1Plus2 = new javax.swing.JButton();
        txtProductItem1Quantity2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlPendingBills = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPendingBills = new javax.swing.JTable();
        pnlPaymentInfo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JLabel();
        txtCustomerPhone = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDiscountCode = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFinalTotal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnProcessPayment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Poly Cafe");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenuLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlMenuLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFullname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFullname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFullname.setText("Họ Tên User");
        pnlMenuLeft.add(lblFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        lblPhoto.setText("Ảnh User");
        pnlMenuLeft.add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 80));

        btnSales.setText("Bán hàng");
        btnSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesActionPerformed(evt);
            }
        });
        pnlMenuLeft.add(btnSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 170, 40));

        btnTrangChu.setText("Trang chủ");
        pnlMenuLeft.add(btnTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 170, 40));

        btnQuanLySP.setText("Quản lý SP");
        pnlMenuLeft.add(btnQuanLySP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 170, 40));

        btnQuanLyHD.setText("Quản lý HĐ");
        pnlMenuLeft.add(btnQuanLyHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 170, 40));

        btnQuanLyNV.setText("Quản lý NV");
        pnlMenuLeft.add(btnQuanLyNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 170, 40));

        btnThongKe.setText("Thống kê");
        pnlMenuLeft.add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 170, 40));

        getContentPane().add(pnlMenuLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 610));

        pnlCurrentBillInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "Giá", "Số lượng"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Mã HĐ:");

        lblCurrentBillId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Thành tiền:");

        lblCurrentBillTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Thông tin hóa đơn");

        javax.swing.GroupLayout pnlCurrentBillInfoLayout = new javax.swing.GroupLayout(pnlCurrentBillInfo);
        pnlCurrentBillInfo.setLayout(pnlCurrentBillInfoLayout);
        pnlCurrentBillInfoLayout.setHorizontalGroup(
            pnlCurrentBillInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCurrentBillInfoLayout.createSequentialGroup()
                .addGroup(pnlCurrentBillInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCurrentBillInfoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCurrentBillInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCurrentBillInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCurrentBillId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCurrentBillTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlCurrentBillInfoLayout.createSequentialGroup()
                                .addGroup(pnlCurrentBillInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 142, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlCurrentBillInfoLayout.setVerticalGroup(
            pnlCurrentBillInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCurrentBillInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCurrentBillInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCurrentBillInfoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCurrentBillId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCurrentBillTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(pnlCurrentBillInfoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        getContentPane().add(pnlCurrentBillInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 500, 290));

        pnlProductListDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlProductListDisplay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlProductItem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblProductItem1Image.setText("jLabel6");
        lblProductItem1Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblProductItem1Name.setText("Bánh mì");

        lblProductItem1Price.setText("20.000 vnd");

        btnProductItem1Minus.setText("-");
        btnProductItem1Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductItem1MinusActionPerformed(evt);
            }
        });

        btnProductItem1Plus.setText("+");
        btnProductItem1Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductItem1PlusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProductItem1Minus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProductItem1Plus))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProductItem1Minus)
                    .addComponent(btnProductItem1Plus))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        txtProductItem1Quantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlProductItem1Layout = new javax.swing.GroupLayout(pnlProductItem1);
        pnlProductItem1.setLayout(pnlProductItem1Layout);
        pnlProductItem1Layout.setHorizontalGroup(
            pnlProductItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductItem1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProductItem1Image, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProductItem1Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProductItem1Price, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addGroup(pnlProductItem1Layout.createSequentialGroup()
                        .addComponent(txtProductItem1Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlProductItem1Layout.setVerticalGroup(
            pnlProductItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductItem1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductItem1Layout.createSequentialGroup()
                        .addComponent(lblProductItem1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProductItem1Price)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProductItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlProductItem1Layout.createSequentialGroup()
                                .addComponent(txtProductItem1Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlProductItem1Layout.createSequentialGroup()
                        .addComponent(lblProductItem1Image, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlProductListDisplay.add(pnlProductItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 230, 130));

        pnlProductItem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblProductItem2Image.setText("jLabel6");
        lblProductItem2Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblProductItem2Price.setText("jLabel13");

        lblProductItem2Name.setText("jLabel12");

        btnProductItem1Minus1.setText("-");
        btnProductItem1Minus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductItem1Minus1ActionPerformed(evt);
            }
        });

        btnProductItem1Plus1.setText("+");
        btnProductItem1Plus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductItem1Plus1ActionPerformed(evt);
            }
        });

        txtProductItem1Quantity1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtProductItem1Quantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProductItem1Minus1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProductItem1Plus1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnProductItem1Minus1)
                        .addComponent(btnProductItem1Plus1))
                    .addComponent(txtProductItem1Quantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlProductItem2Layout = new javax.swing.GroupLayout(pnlProductItem2);
        pnlProductItem2.setLayout(pnlProductItem2Layout);
        pnlProductItem2Layout.setHorizontalGroup(
            pnlProductItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductItem2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProductItem2Image, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProductItem2Name, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addGroup(pnlProductItem2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblProductItem2Price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlProductItem2Layout.setVerticalGroup(
            pnlProductItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductItem2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductItem2Layout.createSequentialGroup()
                        .addComponent(lblProductItem2Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProductItem2Price)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlProductItem2Layout.createSequentialGroup()
                        .addComponent(lblProductItem2Image, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlProductListDisplay.add(pnlProductItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 240, 130));

        pnlProductItem4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblProductItem4Image.setText("jLabel6");
        lblProductItem4Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblProductItem4Name.setText("jLabel12");

        lblProductItem4Price.setText("jLabel13");

        btnProductItem1Minus4.setText("-");
        btnProductItem1Minus4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductItem1Minus4ActionPerformed(evt);
            }
        });

        btnProductItem1Plus4.setText("+");
        btnProductItem1Plus4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductItem1Plus4ActionPerformed(evt);
            }
        });

        txtProductItem1Quantity4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(txtProductItem1Quantity4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProductItem1Minus4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProductItem1Plus4))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProductItem1Minus4)
                    .addComponent(btnProductItem1Plus4)
                    .addComponent(txtProductItem1Quantity4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlProductItem4Layout = new javax.swing.GroupLayout(pnlProductItem4);
        pnlProductItem4.setLayout(pnlProductItem4Layout);
        pnlProductItem4Layout.setHorizontalGroup(
            pnlProductItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductItem4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProductItem4Image, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProductItem4Name, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(lblProductItem4Price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlProductItem4Layout.setVerticalGroup(
            pnlProductItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductItem4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(pnlProductItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductItem4Layout.createSequentialGroup()
                        .addComponent(lblProductItem4Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProductItem4Price)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblProductItem4Image, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlProductListDisplay.add(pnlProductItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 240, 130));

        pnlProductItem3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblProductItem3Image.setText("jLabel6");
        lblProductItem3Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblProductItem3Price.setText("jLabel13");

        lblProductItem3Name.setText("jLabel12");

        btnProductItem1Minus2.setText("-");
        btnProductItem1Minus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductItem1Minus2ActionPerformed(evt);
            }
        });

        btnProductItem1Plus2.setText("+");
        btnProductItem1Plus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductItem1Plus2ActionPerformed(evt);
            }
        });

        txtProductItem1Quantity2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txtProductItem1Quantity2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProductItem1Minus2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProductItem1Plus2))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProductItem1Minus2)
                    .addComponent(btnProductItem1Plus2)
                    .addComponent(txtProductItem1Quantity2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlProductItem3Layout = new javax.swing.GroupLayout(pnlProductItem3);
        pnlProductItem3.setLayout(pnlProductItem3Layout);
        pnlProductItem3Layout.setHorizontalGroup(
            pnlProductItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductItem3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProductItem3Image, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProductItem3Name, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(lblProductItem3Price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlProductItem3Layout.setVerticalGroup(
            pnlProductItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductItem3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(pnlProductItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductItem3Layout.createSequentialGroup()
                        .addComponent(lblProductItem3Image, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(pnlProductItem3Layout.createSequentialGroup()
                        .addComponent(lblProductItem3Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProductItem3Price)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnlProductListDisplay.add(pnlProductItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 130));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Danh sách sản phẩm");
        pnlProductListDisplay.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        getContentPane().add(pnlProductListDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 470, 320));

        pnlPendingBills.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Danh sách hóa đơn chờ");

        tblPendingBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "HD1", "Chờ"}
            },
            new String [] {
                "STT", "Mã HD", "Trạng thái"
            }
        ));
        jScrollPane2.setViewportView(tblPendingBills);

        javax.swing.GroupLayout pnlPendingBillsLayout = new javax.swing.GroupLayout(pnlPendingBills);
        pnlPendingBills.setLayout(pnlPendingBillsLayout);
        pnlPendingBillsLayout.setHorizontalGroup(
            pnlPendingBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPendingBillsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPendingBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlPendingBillsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPendingBillsLayout.setVerticalGroup(
            pnlPendingBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPendingBillsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlPendingBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 260, 290));

        pnlPaymentInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Thông tin thanh toán");

        jLabel7.setText("Tên khách hàng: ");

        txtCustomerName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtCustomerPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("SĐT:");

        txtDiscountCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setText("Mã giảm giá:");

        txtFinalTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("Tổng tiền:");

        btnProcessPayment.setText("Thanh Toán");

        javax.swing.GroupLayout pnlPaymentInfoLayout = new javax.swing.GroupLayout(pnlPaymentInfo);
        pnlPaymentInfo.setLayout(pnlPaymentInfoLayout);
        pnlPaymentInfoLayout.setHorizontalGroup(
            pnlPaymentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPaymentInfoLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(pnlPaymentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPaymentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFinalTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPaymentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDiscountCode, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPaymentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPaymentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addComponent(txtCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
            .addGroup(pnlPaymentInfoLayout.createSequentialGroup()
                .addGroup(pnlPaymentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPaymentInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(pnlPaymentInfoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnProcessPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPaymentInfoLayout.setVerticalGroup(
            pnlPaymentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiscountCode, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFinalTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProcessPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(pnlPaymentInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 290, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalesActionPerformed

    private void btnProductItem1MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductItem1MinusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductItem1MinusActionPerformed

    private void btnProductItem1PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductItem1PlusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductItem1PlusActionPerformed

    private void btnProductItem1Minus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductItem1Minus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductItem1Minus1ActionPerformed

    private void btnProductItem1Plus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductItem1Plus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductItem1Plus1ActionPerformed

    private void btnProductItem1Minus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductItem1Minus2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductItem1Minus2ActionPerformed

    private void btnProductItem1Plus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductItem1Plus2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductItem1Plus2ActionPerformed

    private void btnProductItem1Minus4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductItem1Minus4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductItem1Minus4ActionPerformed

    private void btnProductItem1Plus4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductItem1Plus4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductItem1Plus4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolyCafeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcessPayment;
    private javax.swing.JButton btnProductItem1Minus;
    private javax.swing.JButton btnProductItem1Minus1;
    private javax.swing.JButton btnProductItem1Minus2;
    private javax.swing.JButton btnProductItem1Minus4;
    private javax.swing.JButton btnProductItem1Plus;
    private javax.swing.JButton btnProductItem1Plus1;
    private javax.swing.JButton btnProductItem1Plus2;
    private javax.swing.JButton btnProductItem1Plus4;
    private javax.swing.JButton btnQuanLyHD;
    private javax.swing.JButton btnQuanLyNV;
    private javax.swing.JButton btnQuanLySP;
    private javax.swing.JButton btnSales;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCurrentBillId;
    private javax.swing.JLabel lblCurrentBillTotal;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblProductItem1Image;
    private javax.swing.JLabel lblProductItem1Name;
    private javax.swing.JLabel lblProductItem1Price;
    private javax.swing.JLabel lblProductItem2Image;
    private javax.swing.JLabel lblProductItem2Name;
    private javax.swing.JLabel lblProductItem2Price;
    private javax.swing.JLabel lblProductItem3Image;
    private javax.swing.JLabel lblProductItem3Name;
    private javax.swing.JLabel lblProductItem3Price;
    private javax.swing.JLabel lblProductItem4Image;
    private javax.swing.JLabel lblProductItem4Name;
    private javax.swing.JLabel lblProductItem4Price;
    private javax.swing.JPanel pnlCurrentBillInfo;
    private javax.swing.JPanel pnlMenuLeft;
    private javax.swing.JPanel pnlPaymentInfo;
    private javax.swing.JPanel pnlPendingBills;
    private javax.swing.JPanel pnlProductItem1;
    private javax.swing.JPanel pnlProductItem2;
    private javax.swing.JPanel pnlProductItem3;
    private javax.swing.JPanel pnlProductItem4;
    private javax.swing.JPanel pnlProductListDisplay;
    private javax.swing.JTable tblPendingBills;
    private javax.swing.JLabel txtCustomerName;
    private javax.swing.JLabel txtCustomerPhone;
    private javax.swing.JLabel txtDiscountCode;
    private javax.swing.JLabel txtFinalTotal;
    private javax.swing.JLabel txtProductItem1Quantity;
    private javax.swing.JLabel txtProductItem1Quantity1;
    private javax.swing.JLabel txtProductItem1Quantity2;
    private javax.swing.JLabel txtProductItem1Quantity4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void init() {
        this.setIconImage(XIcon.getIcon("trump-small.png").getImage());

        // Đặt JFrame ra giữa màn hình (đã làm ở phần Người 1)
        this.setLocationRelativeTo(null);

        // Hiển thị cửa sổ chào (WelcomeJDialog)
        this.showWelcomeJDialog(this); // WelcomeJDialog sẽ đóng lại trước khi LoginJDialog hiển thị

        // Hiển thị cửa sổ đăng nhập (LoginJDialog)
        this.showLoginJDialog(this); // LoginJDialog sẽ đóng lại sau khi đăng nhập thành công

        // ----- PHẦN MỚI THÊM BẮT ĐẦU TỪ ĐÂY -----
        // Sau khi LoginJDialog đóng (nghĩa là đăng nhập đã xong hoặc bị hủy),
        // kiểm tra xem người dùng đã đăng nhập thành công chưa (XAuth.user đã được cập nhật)
        if (XAuth.isLogin()) { // Sử dụng phương thức isLogin() từ XAuth
            // Hiển thị họ tên người dùng
            if (lblFullname != null) { // Kiểm tra null để tránh lỗi nếu JLabel chưa được kéo vào form
                lblFullname.setText(XAuth.user.getFullname());
            }

            // Hiển thị ảnh đại diện người dùng
            if (lblPhoto != null && XAuth.user.getPhoto() != null && !XAuth.user.getPhoto().isBlank()) {
                // Giả sử ảnh nằm trong thư mục "photos" bên trong "icons"
                // Hoặc bạn có thể chỉ cần XIcon.getIcon(XAuth.user.getPhoto()) nếu ảnh nằm trực tiếp trong icons
                // Tạm thời, chúng ta sẽ dùng XIcon.setIcon để nó tự scale.
                // Đường dẫn "photos/" là ví dụ từ lab, bạn cần đảm bảo file ảnh người dùng
                // (ví dụ: "trump.png", "admin.png") nằm trong thư mục resources/poly/cafe/icons/photos/
                // HOẶC resources/poly/cafe/icons/ tùy theo cách bạn lưu trữ và XIcon xử lý.
                // Để đơn giản, giả sử ảnh nằm trong icons:
                XIcon.setIcon(lblPhoto, XAuth.user.getPhoto()); // lblPhoto là JLabel trên form
            } else if (lblPhoto != null) {
                lblPhoto.setIcon(null); // Xóa ảnh nếu không có
                lblPhoto.setText("No Photo");
            }

            // Phân quyền: Vô hiệu hóa các nút quản lý nếu không phải là Manager
            // (Giả sử bạn có các nút btnDrinkManager, btnCategoryManager, v.v. đã được khai báo
            // và thêm vào giao diện ở phần Người 1)
            boolean isManager = XAuth.isManager(); // Sử dụng phương thức isManager() từ XAuth

            

            // Các nút chức năng chung như "Bán Hàng", "Lịch Sử", "Đổi Mật Khẩu", "Kết Thúc"
            // thường sẽ luôn được bật cho cả hai vai trò (tùy theo yêu cầu dự án).
            // Ví dụ:
            // if (btnSales != null) btnSales.setEnabled(true);
            // if (btnHistory != null) btnHistory.setEnabled(true);
            // if (btnChangePassword != null) btnChangePassword.setEnabled(true);
            // if (btnExit != null) btnExit.setEnabled(true);

        } else {
            // Nếu người dùng không đăng nhập (ví dụ: đóng LoginJDialog mà không login)
            // Có thể thoát ứng dụng hoặc hiển thị thông báo và yêu cầu đăng nhập lại.
            // Để đơn giản, hiện tại chúng ta có thể thoát.
            XDialog.alert("Bạn chưa đăng nhập. Ứng dụng sẽ thoát.", "Thông báo");
            System.exit(0);
        }
    }
}
